const defaultEvidence=[
  {id:1,title:'React & JavaScript',type:'Technical skill',source:'Final-year web application project',status:'confirmed'},
  {id:2,title:'Data analysis',type:'Transferable skill',source:'Data visualisation coursework',status:'confirmed'},
  {id:3,title:'Team collaboration',type:'Experience',source:'Agile group project',status:'review'},
  {id:4,title:'Stakeholder communication',type:'Transferable skill',source:'Project presentation',status:'review'}
];
const roles=[
  {title:'Junior Software Developer',band:'Strong foundation',matched:['React & JavaScript','Team collaboration'],missing:['Testing framework experience'],uncertain:['API integration'],summary:'A practical starting role for someone with project-based front-end experience.'},
  {title:'Data Analyst',band:'Relevant direction',matched:['Data analysis','Stakeholder communication'],missing:['SQL'],uncertain:['Dashboarding tools'],summary:'Builds on analytical coursework and communication of findings.'},
  {title:'Business Analyst',band:'Relevant direction',matched:['Stakeholder communication','Team collaboration'],missing:['Requirements workshops'],uncertain:['Process mapping'],summary:'An adjacent role centred on translating needs into clear actions.'},
  {title:'QA Analyst',band:'Exploratory match',matched:['Team collaboration','Data analysis'],missing:['Test case design'],uncertain:['Defect tracking'],summary:'A route for structured thinkers interested in product quality.'}
];
let evidence=structuredClone(defaultEvidence),selectedRole=roles[0];
const list=document.querySelector('#evidence-list'), count=document.querySelector('#confirmed-count');
function renderEvidence(){const confirmed=evidence.filter(item=>item.status==='confirmed');count.textContent=`${confirmed.length} confirmed`;list.innerHTML=evidence.map(item=>`<article class="evidence"><div><span class="badge ${item.status}">${item.status==='confirmed'?'Confirmed':'Needs review'}</span><h3>${item.title}</h3><p>${item.type} · “${item.source}”</p></div><div>${item.status==='review'?`<button data-confirm="${item.id}">Confirm</button>`:''}<button data-remove="${item.id}">Remove</button></div></article>`).join('');document.querySelector('#source-one').textContent=`Source: ${confirmed[0]?.source||'Confirm evidence first'}`;document.querySelector('#source-two').textContent=`Source: ${confirmed[1]?.source||'Confirm evidence first'}`;document.querySelector('#letter-one').value=`Show how ${confirmed[0]?.title||'a confirmed skill'} helped you achieve something tangible.`;document.querySelector('#letter-two').value=`Connect ${confirmed[1]?.title||'another example'} to a need in the role description.`}
list.addEventListener('click',event=>{const id=Number(event.target.dataset.confirm||event.target.dataset.remove);if(!id)return;if(event.target.dataset.confirm)evidence=evidence.map(item=>item.id===id?{...item,status:'confirmed'}:item);if(event.target.dataset.remove)evidence=evidence.filter(item=>item.id!==id);renderEvidence()});
document.querySelector('#add-evidence').onclick=()=>{const title=prompt('What evidence would you like to add?');if(title){evidence.push({id:Date.now(),title,type:'Your addition',source:'Added by you',status:'confirmed'});renderEvidence()}};
function detail(role){const group=(title,items,type,symbol)=>`<section class="group ${type}"><h3>${title}</h3>${items.map(x=>`<p><b>${symbol}</b> ${x}</p>`).join('')}</section>`;document.querySelector('#role-detail').innerHTML=`<small>${role.band}</small><h2>${role.title}</h2><p>${role.summary}</p>${group('Matched, confirmed evidence',role.matched,'match','✓')}${group('Not evidenced in this CV',role.missing,'gap','−')}${group('Needs confirmation',role.uncertain,'','?')}<p><small>A gap is an invitation to investigate, not proof you lack a skill.</small></p><a class="button primary" href="#letter">Use this role for planning →</a>`;document.querySelector('#letter-role').textContent=role.title}
function renderRoles(query=''){const matches=roles.filter(role=>role.title.toLowerCase().includes(query.toLowerCase()));document.querySelector('#role-list').innerHTML=matches.map(role=>`<button class="role-card ${role.title===selectedRole.title?'selected':''}" data-role="${role.title}"><span>${role.band}</span><h2>${role.title}</h2><p>${role.summary}</p><small>${role.matched.length} matched evidence areas</small></button>`).join('');document.querySelectorAll('[data-role]').forEach(button=>button.onclick=()=>{selectedRole=roles.find(role=>role.title===button.dataset.role);renderRoles(query);detail(selectedRole)})}
document.querySelector('#role-search').oninput=event=>renderRoles(event.target.value);
document.querySelector('#cv-file').onchange=event=>{const file=event.target.files[0];if(!file)return;document.querySelector('#file-name').textContent=file.name;document.querySelector('#file-help').textContent='Ready for a mock evidence review.';document.querySelector('#review-link').classList.remove('hidden')};
const star=[...document.querySelectorAll('[data-star]')];function updateStar(){const completed=star.filter(item=>item.value.trim()).length,words=star.map(item=>item.value).join(' ').trim().split(/\s+/).filter(Boolean).length;document.querySelector('#progress').textContent=`${completed}/4 parts completed`;document.querySelector('#word-count').textContent=`${words} words`;document.querySelector('#feedback-text').textContent=words<40?'Add detail to make your example easier to follow.':'You have a useful foundation. Check that the actions are clearly yours.'}star.forEach(item=>item.oninput=updateStar);document.querySelector('#clear-star').onclick=()=>{star.forEach(item=>item.value='');updateStar()};
document.querySelector('#topic').onchange=event=>document.querySelector('#question-text').textContent=`Tell me about a time you demonstrated ${event.target.value.toLowerCase()} in a project.`;
document.querySelector('#reset').onclick=()=>{evidence=structuredClone(defaultEvidence);selectedRole=roles[0];renderEvidence();renderRoles();detail(selectedRole);star.forEach(item=>item.value='');updateStar();location.hash='home'};
renderEvidence();renderRoles();detail(selectedRole);updateStar();
