import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const initialEvidence = [
  { id: 1, title: 'React & JavaScript', type: 'Technical skill', source: 'Final-year web application project', status: 'confirmed' },
  { id: 2, title: 'Data analysis', type: 'Transferable skill', source: 'Data visualisation coursework', status: 'confirmed' },
  { id: 3, title: 'Team collaboration', type: 'Experience', source: 'Agile group project', status: 'review' },
  { id: 4, title: 'Stakeholder communication', type: 'Transferable skill', source: 'Project presentation', status: 'review' }
];
const roles = [
  { title: 'Junior Software Developer', band: 'Strong foundation', matched: ['React & JavaScript', 'Team collaboration'], missing: ['Testing framework experience'], uncertain: ['API integration'], summary: 'A practical starting role for someone with project-based front-end experience.' },
  { title: 'Data Analyst', band: 'Relevant direction', matched: ['Data analysis', 'Stakeholder communication'], missing: ['SQL'], uncertain: ['Dashboarding tools'], summary: 'Builds on analytical coursework and communication of findings.' },
  { title: 'Business Analyst', band: 'Relevant direction', matched: ['Stakeholder communication', 'Team collaboration'], missing: ['Requirements workshops'], uncertain: ['Process mapping'], summary: 'An adjacent role centred on translating needs into clear actions.' },
  { title: 'QA Analyst', band: 'Exploratory match', matched: ['Team collaboration', 'Data analysis'], missing: ['Test case design'], uncertain: ['Defect tracking'], summary: 'A route for structured thinkers interested in product quality.' }
];
const nav = [ ['home','Home'], ['upload','CV upload'], ['evidence','Evidence review'], ['roles','Explore roles'], ['letter','Cover letter'], ['interview','Interview practice'] ];

function App() {
  const [page, setPage] = useState('home');
  const [file, setFile] = useState(null);
  const [evidence, setEvidence] = useState(initialEvidence);
  const [selectedRole, setSelectedRole] = useState(roles[0]);
  const [query, setQuery] = useState('');
  const [topic, setTopic] = useState('Teamwork');
  const [star, setStar] = useState({ situation: '', task: '', action: '', result: '' });
  const confirmed = evidence.filter(item => item.status === 'confirmed');
  const filteredRoles = useMemo(() => roles.filter(r => r.title.toLowerCase().includes(query.toLowerCase())), [query]);
  const go = (name) => { setPage(name); window.scrollTo({top:0, behavior:'smooth'}); };
  const reset = () => { setFile(null); setEvidence(initialEvidence); setSelectedRole(roles[0]); setStar({ situation:'',task:'',action:'',result:''}); go('home'); };
  const updateStatus = (id, status) => setEvidence(list => list.map(item => item.id === id ? {...item, status} : item));
  const removeEvidence = id => setEvidence(list => list.filter(item => item.id !== id));
  const words = Object.values(star).join(' ').trim().split(/\s+/).filter(Boolean).length;

  return <div className="app-shell">
    <header><button className="brand" onClick={() => go('home')}><span>✦</span> Career Evidence</button><nav>{nav.slice(1).map(([key,label]) => <button key={key} className={page===key?'active':''} onClick={() => go(key)}>{label}</button>)}</nav><button className="reset" onClick={reset}>Reset demo</button></header>
    <main>
      {page === 'home' && <section className="hero">
        <div className="eyebrow">AI Career Assistant for Graduates</div><h1>Turn what you’ve done into evidence you can use.</h1><p className="lead">A calm, candidate-controlled space to review your CV, explore suitable roles and prepare grounded applications.</p><div className="hero-actions"><button className="primary" onClick={() => go('upload')}>Start with your CV <b>→</b></button><button className="secondary" onClick={() => go('roles')}>Explore the demo</button></div>
        <div className="principles"><article><i>◌</i><h3>Inspectable evidence</h3><p>See the source behind every suggestion.</p></article><article><i>⌕</i><h3>Edit or delete anything</h3><p>You stay in control of your information.</p></article><article><i>◇</i><h3>Advice, not a decision</h3><p>Role relevance is not a hiring outcome.</p></article></div>
        <div className="journey"><span>Your journey</span>{['Upload CV','Review evidence','Explore roles','Plan letter','Practise interview'].map((x,i) => <React.Fragment key={x}><button onClick={() => go(nav[i+1][0])}><b>{i+1}</b>{x}</button>{i<4 && <em>→</em>}</React.Fragment>)}</div>
        <p className="disclaimer">Not found in a CV does not mean a skill is absent. This demonstration uses mock data and does not make employability or hiring decisions.</p>
      </section>}
      {page === 'upload' && <section className="page narrow"><Step title="Start with your CV" number="01" text="Upload a CV to identify evidence you can inspect before you receive any advice."/><div className="upload-box"><div className="upload-icon">↑</div><h2>{file ? file.name : 'Drop your CV here'}</h2><p>{file ? 'Ready for a mock evidence review.' : 'PDF, DOC or DOCX - your file stays in this browser for this demo.'}</p><label className="primary">Choose a file<input type="file" accept=".pdf,.doc,.docx" hidden onChange={e => setFile(e.target.files?.[0] || null)}/></label>{file && <button className="secondary" onClick={() => go('evidence')}>Review extracted evidence →</button>}</div><aside className="note"><b>Privacy first</b><span>Names and contact details are not used for role exploration. In this demo, no file is sent anywhere.</span></aside></section>}
      {page === 'evidence' && <section className="page"><Step title="Review your evidence" number="02" text="Confirm, correct or remove the information the demo found. Only confirmed evidence is used in planning."/><div className="two-col"><div><div className="section-title"><h2>Extracted from your CV</h2><span>{confirmed.length} confirmed</span></div><div className="evidence-list">{evidence.map(item => <article className="evidence" key={item.id}><div><span className={'status '+item.status}>{item.status === 'confirmed' ? 'Confirmed' : 'Needs review'}</span><h3>{item.title}</h3><p>{item.type} · <q>{item.source}</q></p></div><div className="evidence-actions">{item.status !== 'confirmed' && <button onClick={() => updateStatus(item.id,'confirmed')}>Confirm</button>}<button onClick={() => removeEvidence(item.id)}>Remove</button></div></article>)}</div><button className="add" onClick={() => setEvidence(list => [...list, {id:Date.now(),title:'New evidence',type:'Your addition',source:'Added by you',status:'confirmed'}])}>+ Add evidence</button></div><aside className="panel"><h3>Why review first?</h3><p>This keeps the next steps grounded in things you recognise and can stand behind.</p><button className="primary" onClick={() => go('roles')}>Explore roles →</button></aside></div></section>}
      {page === 'roles' && <section className="page"><Step title="Explore roles" number="03" text="Compare roles through visible evidence, not an opaque employability score."/><div className="role-layout"><div><label className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles"/></label><div className="role-list">{filteredRoles.map(role => <button className={'role-card '+(selectedRole.title===role.title?'selected':'')} key={role.title} onClick={() => setSelectedRole(role)}><span>{role.band}</span><h3>{role.title}</h3><p>{role.summary}</p><small>{role.matched.length} matched evidence areas</small></button>)}</div></div><RoleDetail role={selectedRole} onContinue={() => go('letter')}/></div></section>}
      {page === 'letter' && <section className="page"><Step title="Plan your cover letter" number="04" text="Use confirmed evidence to create a clear outline - not claims you cannot support."/><div className="two-col"><div className="letter"><div className="letter-header"><div><span>Planning for</span><h2>{selectedRole.title}</h2></div><span className="wordcount">Outline · 4 sections</span></div><Plan title="Opening" source="Your motivation" defaultValue={`I am writing to apply for the ${selectedRole.title} role because I am keen to build on my project-based experience.`}/><Plan title="Evidence point 1" source={confirmed[0]?.source || 'Confirm evidence first'} defaultValue={`Show how ${confirmed[0]?.title || 'a confirmed skill'} helped you achieve something tangible.`}/><Plan title="Evidence point 2" source={confirmed[1]?.source || 'Confirm evidence first'} defaultValue={`Connect ${confirmed[1]?.title || 'another example'} to a need in the role description.`}/><Plan title="Closing" source="Your next step" defaultValue="Invite a conversation and thank the reader for their time."/></div><aside className="panel"><h3>Keep it truthful</h3><p>This plan draws from confirmed CV evidence. Edit it to reflect your voice and research the organisation before writing.</p><button className="primary" onClick={() => go('interview')}>Practise an interview →</button></aside></div></section>}
      {page === 'interview' && <section className="page"><Step title="Interview practice" number="05" text="Practise structuring a real example with STAR. This is reflection support, not a judgement of personality or ability."/><div className="interview-top"><label>Competency <select value={topic} onChange={e=>setTopic(e.target.value)}>{['Teamwork','Problem solving','Communication','Adaptability'].map(x=><option key={x}>{x}</option>)}</select></label><div><span>Practice progress</span><b>{Object.values(star).filter(Boolean).length}/4 parts completed</b></div></div><article className="question"><span>Question</span><h2>Tell me about a time you demonstrated {topic.toLowerCase()} in a project.</h2><p>Use an example you can explain comfortably. You can change or leave any field blank.</p></article><div className="star-grid">{[['situation','Situation','Set the context: where and when?'],['task','Task','What were you responsible for?'],['action','Action','What did you specifically do?'],['result','Result','What changed or what did you learn?']].map(([key,title,placeholder])=><label key={key}><span>{title}</span><textarea value={star[key]} placeholder={placeholder} onChange={e=>setStar({...star,[key]:e.target.value})}/></label>)}</div><div className="feedback"><div><b>{words} words</b><span>{words < 40 ? 'Add a little detail to make your example easier to follow.' : 'You have a useful foundation. Check that the actions are clearly yours.'}</span></div><button className="secondary" onClick={() => setStar({situation:'',task:'',action:'',result:''})}>Clear answer</button></div></section>}
    </main><footer>Demonstration only · Uses mock data · Candidate-controlled advice</footer>
  </div>
}
function Step({title,number,text}) { return <div className="step"><span>{number}</span><div><h1>{title}</h1><p>{text}</p></div></div> }
function RoleDetail({role,onContinue}) { return <aside className="role-detail"><span className="band">{role.band}</span><h2>{role.title}</h2><p>{role.summary}</p><EvidenceGroup title="Matched, confirmed evidence" items={role.matched} type="match"/><EvidenceGroup title="Not evidenced in this CV" items={role.missing} type="gap"/><EvidenceGroup title="Needs confirmation" items={role.uncertain} type="uncertain"/><p className="caveat">A gap is an invitation to investigate, not proof you lack a skill.</p><button className="primary" onClick={onContinue}>Use this role for planning →</button></aside> }
function EvidenceGroup({title,items,type}) { return <div className={'evidence-group '+type}><h3>{title}</h3>{items.map(x=><p key={x}> <b>{type==='match'?'✓':type==='gap'?'−':'?'}</b> {x}</p>)}</div> }
function Plan({title,source,defaultValue}) { const [value,setValue]=useState(defaultValue); return <label className="plan"><span>{title}<small>Source: {source}</small></span><textarea value={value} onChange={e=>setValue(e.target.value)}/></label> }
createRoot(document.getElementById('root')).render(<App/>);
